version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: 'gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab'
        gitlab_rails['initial_root_password'] = 'Bubilda12345678'
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
      - "53:53"
    volumes:
      - ./gitlab_self_hosted/gitlab/config:/etc/gitlab
      - ./gitlab_self_hosted/gitlab/logs:/var/log/gitlab
      - ./gitlab_self_hosted/gitlab/data:/var/opt/gitlab
    networks:
      - gitlab-net

  work_environment:
    image: ci-cd-work-environment:1.1
    container_name: work-environment-container-1.1
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      gitlab:
        condition: service_healthy
    networks:
      - gitlab-net

networks:
  gitlab-net:
    driver: bridge