stages:          
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Build image..."
    - docker build -t bubilda-image:latest .
    - echo "Build image complete."

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests... This will take about 10 seconds."
    - sleep 10
    - echo "Code coverage is 90%"

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Stoping and remooving old container"
    - docker stop bubilda-container
    - docker rm bubilda-container
    - echo "Build image complete."
    - echo "Deploying application, start container complete."
    - docker run -d --name bubilda-container -p 8081:8081 bubilda-image:latest
    - echo "Application successfully deployed, container is running"
